import type { Video } from "../../types/video";

/**
 * Sample feed shown to signed-out visitors.
 *
 * Field shapes match what /api/videos returns — raw view counts, ISO-8601
 * durations, ISO dates — so the UI has a single formatting path. These used to
 * be pre-formatted strings ("9.6M", "17:04", "7 years ago"), which meant
 * formatViewCount/formatDuration silently produced different output depending
 * on whether a video came from the API or from this list.
 */
export const DEMO_VIDEOS: Video[] = [
  {
    id: "JRHAM1nAuD4",
    channelId: "UCZ9qFEC82qM6Pk-54Q4TVWA",
    title: "Artificial Intelligence | Research and Which Majors to Pick",
    thumbnail: "https://i.ytimg.com/vi/JRHAM1nAuD4/mqdefault.jpg",
    duration: "PT18M32S",
    channelName: "Zach Star",
    views: "172000",
    publishedAt: "2019-03-12T00:00:00.000Z",
    watched: false,
    inLibrary: false,
    description:
      "An overview of AI research areas and which majors lead into them.",
  },
  {
    id: "WUvTyaaNkzM",
    channelId: "UCYO_jab_esuFRV4b17AJtAw",
    title: "The essence of calculus",
    thumbnail: "https://i.ytimg.com/vi/WUvTyaaNkzM/mqdefault.jpg",
    duration: "PT17M4S",
    channelName: "3Blue1Brown",
    views: "9600000",
    publishedAt: "2017-04-28T00:00:00.000Z",
    watched: false,
    inLibrary: false,
    description: "A visual introduction to the core ideas behind calculus.",
  },
  {
    id: "p7HKvqRI_Bo",
    channelId: "UCsooa4yRKGN_zEE8iknghZA",
    title: "How does the stock market work? - Oliver Elfenbaum",
    thumbnail: "https://i.ytimg.com/vi/p7HKvqRI_Bo/mqdefault.jpg",
    duration: "PT4M29S",
    channelName: "TED-Ed",
    views: "567000",
    publishedAt: "2019-08-19T00:00:00.000Z",
    watched: false,
    inLibrary: false,
    description: "A short explainer on how shares and stock markets function.",
  },
  {
    id: "Rt6beTKDtqY",
    channelId: "UCZ9qFEC82qM6Pk-54Q4TVWA",
    title: "The Mathematics of Machine Learning",
    thumbnail: "https://i.ytimg.com/vi/Rt6beTKDtqY/mqdefault.jpg",
    duration: "PT16M33S",
    channelName: "Zach Star",
    views: "488000",
    publishedAt: "2019-11-15T00:00:00.000Z",
    watched: false,
    inLibrary: false,
    description:
      "The linear algebra, calculus and statistics behind machine learning.",
  },
  {
    id: "fkAAbXPEAtU",
    channelId: "UC7DdEm33SyaTDtWYGO2CwdA",
    title: "Quantum Entanglement Explained Simply",
    thumbnail: "https://i.ytimg.com/vi/fkAAbXPEAtU/mqdefault.jpg",
    duration: "PT9M56S",
    channelName: "Science ABC",
    views: "786000",
    publishedAt: "2021-02-10T00:00:00.000Z",
    watched: false,
    inLibrary: false,
    description:
      "What entanglement is, without the usual pop-science hand-waving.",
  },
  {
    id: "Qqe4thU-os8",
    channelId: "UCb1GdqUqArXMQ3RS86lqqOw",
    title: "DNA Replication (Updated)",
    thumbnail: "https://i.ytimg.com/vi/Qqe4thU-os8/mqdefault.jpg",
    duration: "PT8M11S",
    channelName: "Amoeba Sisters",
    views: "7700000",
    publishedAt: "2020-07-14T00:00:00.000Z",
    watched: false,
    inLibrary: false,
    description: "A walkthrough of the DNA replication process.",
  },
  {
    id: "F1cghFu9zBs",
    channelId: "UCV6KDgJskWaEckne5aPA0aQ",
    title: "How To Build Wealth In Your 20s (Realistically)",
    thumbnail: "https://i.ytimg.com/vi/F1cghFu9zBs/mqdefault.jpg",
    duration: "PT14M33S",
    channelName: "Graham Stephan",
    views: "290000",
    publishedAt: "2025-10-20T00:00:00.000Z",
    watched: false,
    inLibrary: false,
    description:
      "Practical personal-finance steps for people early in their careers.",
  },
  {
    id: "e-P5IFTqB98",
    channelId: "UCsXVk37bltHxD1rDPwtNM8Q",
    title: "Black Holes Explained - From Birth to Death",
    thumbnail: "https://i.ytimg.com/vi/e-P5IFTqB98/mqdefault.jpg",
    duration: "PT5M55S",
    channelName: "Kurzgesagt - In a Nutshell",
    views: "25000000",
    publishedAt: "2015-12-03T00:00:00.000Z",
    watched: false,
    inLibrary: false,
    description:
      "The full life cycle of a black hole, from formation to evaporation.",
  },
  {
    id: "yZvFH7B6gKI",
    channelId: "UCz8J7E5w3Wp3yFoZpC3y7mw",
    title: "What Is Data Analytics? - An Introduction (Full Guide)",
    thumbnail: "https://i.ytimg.com/vi/yZvFH7B6gKI/mqdefault.jpg",
    duration: "PT9M4S",
    channelName: "CareerFoundry",
    views: "1500000",
    publishedAt: "2022-06-08T00:00:00.000Z",
    watched: false,
    inLibrary: false,
    description:
      "An introduction to the data analytics field and its workflow.",
  },
  {
    id: "fE_QTn4daPU",
    channelId: "UCUMZ7gohGI9HcU9VNsr2FJQ",
    title: "The Science Behind Climate Change, Explained in 2 Minutes",
    thumbnail: "https://i.ytimg.com/vi/fE_QTn4daPU/mqdefault.jpg",
    duration: "PT1M47S",
    channelName: "Bloomberg Originals",
    views: "35000",
    publishedAt: "2015-11-30T00:00:00.000Z",
    watched: false,
    inLibrary: false,
    description:
      "A two-minute summary of the physical basis of climate change.",
  },
  {
    id: "ReFqFPJHLhA",
    channelId: "UCn7dB9UMTBDjKtEKBy_XISw",
    title: "Heuristics and biases in decision making, explained",
    thumbnail: "https://i.ytimg.com/vi/ReFqFPJHLhA/mqdefault.jpg",
    duration: "PT3M48S",
    channelName: "Learn Liberty",
    views: "631000",
    publishedAt: "2018-01-25T00:00:00.000Z",
    watched: false,
    inLibrary: false,
    description: "How cognitive shortcuts systematically distort decisions.",
  },
  {
    id: "TImdsUglGv4",
    channelId: "UCW4J0Z1pL9J4G9Uq8i4e0wA",
    title: "How Encryption Works - and How It Can Be Bypassed",
    thumbnail: "https://i.ytimg.com/vi/TImdsUglGv4/mqdefault.jpg",
    duration: "PT2M48S",
    channelName: "The Wall Street Journal",
    views: "5000000",
    publishedAt: "2016-03-01T00:00:00.000Z",
    watched: false,
    inLibrary: false,
    description: "The basics of encryption and the ways it gets circumvented.",
  },
];
